image: docker:latest

services:
  - docker:dind

variables:
  LATEST_VER_HML: caleberios/gaia-gateway:homolog
  LATEST_VER_PROD: caleberios/gaia-gateway:latest

stages:
  - build
  - test
  - quality
  - deploy

buildLocal:
  stage: build
  script:
    - docker build -t gaiagateway .

testCheck:
  stage: test
  script:
    - docker build -t gaiagateway .
    - docker run --rm -v $PWD:/app -v /app/node_modules gaiagateway npm run test

staticAnalysis:
  stage: quality
  script:
    - docker build -t gaiagateway .
    - docker run --rm -v $PWD:/app -v /app/node_modules gaiagateway npm run lint

deployHomolog:
  stage: deploy
  only:
    - dev
  script:
    - docker build -t $LATEST_VER_HML .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_HML && docker image rm $LATEST_VER_HML

deployProd:
  stage: deploy
  only:
    - master
  script:
    - docker build -t $LATEST_VER_PROD .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_PROD && docker image rm $LATEST_VER_PROD
